package com.adaptris.profiler.client;

import java.util.List;

import com.adaptris.profiler.InterlokProfilerPlugin;

public interface ClientPlugin extends InterlokProfilerPlugin {

  /**
   * Return a list of receivers that will receive events generated by the various profiler aspects.
   * 
   * @return a list of receivers that will be sent events.
   */
  List<EventReceiver> getReceivers();

}
