package com.adaptris.profiler.client;

import com.adaptris.profiler.ProcessStep;

/**
 * Listener that receives events generated by the various aspects.
 * 
 * @author amcgrath
 * 
 */
public interface EventReceiver {
  
  /**
   * Handle the event.
   * 
   * @param processStep the {@link ProcessStep}
   */
  void onEvent(ProcessStep processStep);

}
